//! Hello World - Minimal Zignocchio Example
//!
//! This is the simplest possible Solana program using the Zignocchio framework.

const sdk = @import("sdk");

const Accounts = struct {};

const Program = struct {
    pub const max_accounts = 1;

    pub const Instruction = .{
        .{
            .name = "hello",
            .accounts = Accounts,
            .handler = hello,
            .allow_empty = true,
        },
    };
};

/// Program entrypoint generated by the framework dispatcher.
export fn entrypoint(input: [*]u8) u64 {
    return @call(.always_inline, sdk.exportProgram(Program), .{input});
}

/// Hello instruction handler.
fn hello(
    _: sdk.Context(Accounts),
    _: []const u8,
) sdk.ProgramResult {
    var message: [22]u8 = undefined;
    message[0] = 'H';
    message[1] = 'e';
    message[2] = 'l';
    message[3] = 'l';
    message[4] = 'o';
    message[5] = ' ';
    message[6] = 'f';
    message[7] = 'r';
    message[8] = 'o';
    message[9] = 'm';
    message[10] = ' ';
    message[11] = 'Z';
    message[12] = 'i';
    message[13] = 'g';
    message[14] = 'n';
    message[15] = 'o';
    message[16] = 'c';
    message[17] = 'c';
    message[18] = 'h';
    message[19] = 'i';
    message[20] = 'o';
    message[21] = '!';
    sdk.logMsg(message[0..]);
    return {};
}
